language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-abb-wpbone' ]; then cd .. && eval "mv $currentfolder generator-abb-wpbone" && cd generator-abb-wpbone; fi

